export const CREATE_CATEGORY_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CATEGORY_ASSET_SUCCESS';
export const CREATE_CATEGORY_FAIL = 'CATEGORY_ASSET_FAIL';

export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_CATEGORIES_REQUEST';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAIL = 'GET_ALL_CATEGORIES_FAIL';

export const STORE_CATEGORY = 'STORE_CATEGORY';
export const REMOVE_STORE_CATEGORY = 'REMOVE_STORE_CATEGORY';

export const EDIT_CATEGORY_REQUEST = 'EDIT_CATEGORY_REQUEST';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_REQUEST';
export const EDIT_CATEGORY_FAIL = 'EDIT_CATEGORY_REQUEST';

export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';
