export const CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAIL = 'CREATE_COURSE_FAIL';

export const GET_ALL_COURSE_REQUEST = 'GET_ALL_COURSE_REQUEST';
export const GET_ALL_COURSE_SUCCESS = 'GET_ALL_COURSE_SUCCESS';
export const GET_ALL_COURSE_FAIL = 'GET_ALL_COURSE_FAIL';

export const STORE_COURSE = 'STORE_COURSE';
export const REMOVE_STORE_COURSE = 'REMOVE_STORE_COURSE';

export const EDIT_COURSE_REQUEST = 'EDIT_COURSE_REQUEST';
export const EDIT_COURSE_SUCCESS = 'EDIT_COURSE_REQUEST';
export const EDIT_COURSE_FAIL = 'EDIT_COURSE_REQUEST';

export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAIL = 'GET_COURSE_FAIL';

export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_REQUEST';
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_REQUEST';
