export const CREATE_FIELD_REQUEST = 'CREATE_FIELD_REQUEST';
export const CREATE_FIELD_SUCCESS = 'CREATE_FIELD_SUCCESS';
export const CREATE_FIELD_FAIL = 'CREATE_FIELD_FAIL';

export const GET_ALL_FIELD_REQUEST = 'GET_ALL_FIELD_REQUEST';
export const GET_ALL_FIELD_SUCCESS = 'GET_ALL_FIELD_SUCCESS';
export const GET_ALL_FIELD_FAIL = 'GET_ALL_FIELD_FAIL';

export const STORE_FIELD = 'STORE_FIELD';
export const REMOVE_STORE_FIELD = 'REMOVE_STORE_FIELD';

export const EDIT_FIELD_REQUEST = 'EDIT_FIELD_REQUEST';
export const EDIT_FIELD_SUCCESS = 'EDIT_FIELD_REQUEST';
export const EDIT_FIELD_FAIL = 'EDIT_FIELD_REQUEST';

export const GET_FIELD_REQUEST = 'GET_FIELD_REQUEST';
export const GET_FIELD_SUCCESS = 'GET_FIELD_SUCCESS';
export const GET_FIELD_FAIL = 'GET_FIELD_FAIL';

export const DELETE_FIELD_REQUEST = 'DELETE_FIELD_REQUEST';
export const DELETE_FIELD_SUCCESS = 'DELETE_FIELD_REQUEST';
export const DELETE_FIELD_FAIL = 'DELETE_FIELD_REQUEST';
